In [4]:
import json
import boto3

def put_image_in_s3(media, bucket_name, object_key):
    s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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", region_name='eu-west-1')

    try:
        s3.put_object(Bucket=bucket_name, Key=object_key, Body=media)
        print("Media uploaded successfully to S3")
    except Exception as e:
        print(f"An error occurred: {e}")

def read_and_upload_json(file_path, bucket_name, object_key):
    with open(file_path, 'r') as file:
        json_data = json.load(file)
    
    json_str = json.dumps(json_data)

    json_bytes = json_str.encode('utf-8')

    put_image_in_s3(json_bytes, bucket_name, object_key)

file_path = 'video_info.json'
bucket_name = 'soulchain-dev1-output-video'
object_key = 'video_info.json'

read_and_upload_json(file_path, bucket_name, object_key)

Media uploaded successfully to S3

In [4]:
import boto3

def read_txt_from_s3(bucket_name, file_key):
    s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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", region_name='eu-west-1')
    
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    
    text = obj['Body'].read().decode('utf-8')
    
    return text

# Example usage
bucket_name = 'soulchain-dev1-output-video'
file_key = 'example.txt'
file_content = read_txt_from_s3(bucket_name, file_key)
print(file_content)

topic_found ad image found

In [3]:
from manual_generation import split_text
from topic import find_topics
import boto3
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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")
lang="French"
user_id="user18494"
video_id= f"video_{user_id}"
df=find_topics("Nature's tranquility envelops us, with whispering trees and singing birds. Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly. Majestic mountains reach for the sky, while stars twinkle overhead. In nature's embrace, peace reigns, offering a timeless sanctuary for all.")
split_text(s3,lang,df,user_id,video_id)

English
data: {'text': "Nature's tranquility envelops us, with whispering trees and singing birds.", 'source': 'English', 'target': 'French'}
English
data: {'text': 'Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly.', 'source': 'English', 'target': 'French'}
English
data: {'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.', 'source': 'English', 'target': 'French'}
English
data: {'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.", 'source': 'English', 'target': 'French'}

{'video_id': 'video_user18494',
 'user_id': 'user18494',
 'date_created': '2024-07-03T14:42:27.625205',
 'video_key': 'generated_videos/video_user18494/final_video.mp4',
 'video_type': 'image',
 'video_parts': [{'key': 1,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video_user18494/audio1',
   'text': "Nature's tranquility envelops us, with whispering trees and singing birds.",
   'subtitles': 'La tranquillité de la nature nous enveloppe, avec des arbres murmurants et des oiseaux chantants.',
   'video_part_key': 'generated_videos/video_user18494/video_user18494_part_1.mp4'},
  {'key': 2,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video_user18494/audio2',
   'text': 'Rivers flow gently, sunlight paints warmth, and flowers bloom vibrantly.',
   'subtitles': 'Les rivières coulent doucement, le soleil peint la chaleur, et les fleurs fleurissent avec éclat.',
   'video_part_key': 'generated_videos/video_user18494/video_user18494_part_2.mp4'},
  {'key': 3,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video_user18494/audio3',
   'text': 'Majestic mountains reach for the sky, while stars twinkle overhead.',
   'subtitles': 'Des montagnes majestueuses atteignent le ciel, tandis que des étoiles brillent au-dessus.',
   'video_part_key': 'generated_videos/video_user18494/video_user18494_part_3.mp4'},
  {'key': 4,
   'duration': 0,
   'media_key': '',
   'audio_key': 'generated_videos/video_user18494/audio4',
   'text': "In nature's embrace, peace reigns, offering a timeless sanctuary for all.",
   'subtitles': "Dans l'étreinte de la nature, la paix règne, offrant un sanctuaire intemporel pour tous.",
   'video_part_key': 'generated_videos/video_user18494/video_user18494_part_4.mp4'}]}

In [26]:
from botocore.exceptions import ClientError

import pandas as pd
df=[]
try:
    response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

    data = json.loads(response['Body'].read())
except ClientError as e:
    if e.response['Error']['Code'] == 'NoSuchKey':
        data = []
    else:
        raise
video = next((v for v in data if v["video_id"] == video_id), None)

all_keys = []
if video and "video_parts" in video:
    final_keys = [part['key'] for part in video['video_parts']]

if video:
    for final_key in final_keys:
        part = next((p for p in video["video_parts"] if p["key"] == final_key), None)
        df.append({
                    'sentence':part["text"],
                    'sentence_part_id':part["key"]
                })
        
df=pd.DataFrame(df)    

generate_audio(df, video_id)

In [28]:
df=pd.DataFrame(df)

In [29]:
df

                                            sentence  sentence_part_id
0  Nature's tranquility envelops us, with whisper...                 1
1  Rivers flow gently, sunlight paints warmth, an...                 2
2  Majestic mountains reach for the sky, while st...                 3
3  In nature's embrace, peace reigns, offering a ...                 4

In [36]:
from datalake import read_metadata_from_s3
new_media_paths=["datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-30e9-4ff5-a33e-2f64122101f7"]
session = boto3.Session(region_name='eu-west-1')
s3 = session.client('s3',aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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")

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata_mixkit_unsplash_pixabay.xlsx") 
metadata["tendency_score"]=0   

for path in new_media_paths:
    metadata.loc[metadata["path_datalake"] == path, "tendency_score"] += 1

In [38]:
metadata.iloc[15:22]

    Unnamed: 0             name  ... media_state tendency_score
15          15  6CmVVayeUBQ.jpg  ...      useful              0
16          16  Yhkiy-vVo2w.jpg  ...      useful              0
17          17  Bdf-d5CaWFE.jpg  ...      useful              0
18          18  Ow4X45p6mIw.jpg  ...      useful              0
19          19  FxU8KV7psMY.jpg  ...      useful              0
20          20  wVMBn5sPQt0.jpg  ...      useful              0
21          21  46P3SPTkZqQ.jpg  ...      useful              0

[7 rows x 15 columns]

In [3]:
from text_to_media import find_media_best
from datalake import read_metadata_from_s3

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "metadata_mixkit_unsplash_pixabay.xlsx")

find_media_best(['illness', 'eating', 'foods', 'body', 'cope'],[],metadata)

(True,
 True,
 ['datalake_media/image-body-116585_150.jpg-fa398ea4-69ff-45cc-b377-40168b6c0886',
  'datalake_media/image-overweight-3018731_150.jpg-aa807065-2251-42e5-835c-1ea2acaf9c10',
  'datalake_media/video-health-dab93dec-61e6-46e8-8b39-6d99e40e67ac'])

In [7]:
new_media_paths = [
    [
        "https://eu-west-1.console.aws.amazon.com/s3/object/soulchain-dev1-output-video?bucketType=general&prefix=datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81",
        "https://eu-west-1.console.aws.amazon.com/s3/object/soulchain-dev1-output-video?bucketType=general&prefix=datalake_media/image-whOkVvf0_hU.jpg-98080df6-51fc-41ed-a7fb-5e3066debdd5"
    ]
]

if new_media_paths and isinstance(new_media_paths, list):
    updated_media_paths = []
    
    for sublist in new_media_paths:
        if isinstance(sublist, list):
            updated_sublist = []
            for path in sublist:
                if isinstance(path, str):
                    start_index = path.find("datalake_media")
                    
                    if start_index != -1:
                        end_index = path.find("?", start_index)
                        
                        if end_index != -1:
                            updated_sublist.append(path[start_index:end_index])
                        else:
                            updated_sublist.append(path[start_index:])
            updated_media_paths.append(updated_sublist)
        else:
            updated_media_paths.append(sublist)
    
    new_media_paths = updated_media_paths
else:
    new_media_paths = []

In [9]:
new_media_paths

[['datalake_media/image-digital-marketing-1725340_150.jpg-785e05fd-a610-4695-bc63-a660b1899a81',
  'datalake_media/image-whOkVvf0_hU.jpg-98080df6-51fc-41ed-a7fb-5e3066debdd5']]

In [2]:
import boto3
import subprocess
from concurrent.futures import ThreadPoolExecutor

# Initialize boto3 client
s3 = boto3.client(
    's3',
    aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",
    aws_secret_access_key="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",
    region_name='eu-west-1'
)

# Define S3 paths and local filenames
s3_audio_bucket = 'soulchain-dev1-output-video'
s3_audio_key = 'generated_videos/video_user_imane/audio1'
s3_image_bucket = 'soulchain-dev1-output-video'
s3_image_key = 'datalake_media/image--_S3mOGFzRU.jpg-c7ac1cb5-4639-4c50-b9a4-31cf8ececb51'
local_audio_path = 'audiofile.mp3'
local_image_path = 'imagefile.jpg'
output_video_path = 'output.mp4'

def download_file(bucket, key, local_path):
    s3.download_file(bucket, key, local_path)

with ThreadPoolExecutor() as executor:
    executor.submit(download_file, s3_audio_bucket, s3_audio_key, local_audio_path)
    executor.submit(download_file, s3_image_bucket, s3_image_key, local_image_path)

# Create video using FFmpeg
ffmpeg_command = [
    'ffmpeg',
    '-y',  # Overwrite output files without asking
    '-loop', '1',
    '-i', local_image_path,
    '-i', local_audio_path,
    '-c:v', 'libx264',
    '-tune', 'stillimage',
    '-c:a', 'aac',
    '-b:a', '192k',
    '-pix_fmt', 'yuv420p',
    '-shortest',
    output_video_path
]

subprocess.run(ffmpeg_command)

ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, image2, from 'imagefile.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 478684 kb/s
  Stream #0:0: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 2656x3984 [SAR 72:72 DAR 2:3], 25 fps, 25 tbr, 25 tbn
[aist#1:0/pcm_s16le @ 0x145623170] Guessed Channel Layout: mono
Input #1, wav, from 'audiofile.mp3':
  Duration: 00:00:11.23, bitrate: 384 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, mono, s16, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[aac @ 0x146806d60] Too many bits 8192.000000 > 6144 per frame requested, clamping to max
[swscaler @ 0x128cd8000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x138af0000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x128cb8000] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 1 times
[libx264 @ 0x145626cc0] using SAR=1/1
[libx264 @ 0x145626cc0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x145626cc0] profile High, level 6.0, 4:2:0, 8-bit
[libx264 @ 0x145626cc0] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:-3:-3 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=2.00:0.70 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-4 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.20
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 2656x3984 [SAR 1:1 DAR 2:3], q=2-31, 25 fps, 12800 tbn
      Metadata:
        encoder         : Lavc61.3.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 24000 Hz, mono, fltp, 144 kb/s
      Metadata:
        encoder         : Lavc61.3.100 aac
[out#0/mp4 @ 0x1456232e0] video:6117KiB audio:151KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.130778%
frame=  280 fps= 14 q=-1.0 Lsize=    6277KiB time=00:00:11.12 bitrate=4624.2kbits/s speed=0.563x
[libx264 @ 0x145626cc0] frame I:2     Avg QP:15.57  size:2067394
[libx264 @ 0x145626cc0] frame P:71    Avg QP:16.81  size: 27507
[libx264 @ 0x145626cc0] frame B:207   Avg QP:26.28  size:   849
[libx264 @ 0x145626cc0] consecutive B-frames:  1.4%  0.0%  0.0% 98.6%
[libx264 @ 0x145626cc0] mb I  I16..4:  0.0% 98.4%  1.5%
[libx264 @ 0x145626cc0] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  5.7%  0.0%  0.1%  0.0%  0.0%    skip:94.1%
[libx264 @ 0x145626cc0] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  1.9%  0.0%  0.0%  direct: 0.0%  skip:98.1%  L0:65.3% L1:34.3% BI: 0.4%
[libx264 @ 0x145626cc0] 8x8 transform intra:98.4% inter:87.1%
[libx264 @ 0x145626cc0] coded y,uvDC,uvAC intra: 99.9% 77.9% 56.2% inter: 0.9% 0.6% 0.0%
[libx264 @ 0x145626cc0] i16 v,h,dc,p:  0%  0% 17% 83%
[libx264 @ 0x145626cc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 11%  8% 24%  8% 10% 10%  9% 10% 10%
[libx264 @ 0x145626cc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 11%  8% 11% 10% 14% 12% 11% 12% 11%
[libx264 @ 0x145626cc0] i8c dc,h,v,p: 52% 17% 23%  8%
[libx264 @ 0x145626cc0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x145626cc0] ref P L0: 83.5%  0.0% 16.1%  0.3%
[libx264 @ 0x145626cc0] ref B L0: 52.8% 46.5%  0.6%
[libx264 @ 0x145626cc0] ref B L1: 96.7%  3.3%
[libx264 @ 0x145626cc0] kb/s:4473.94
[aac @ 0x146806d60] Qavg: 61922.281

CompletedProcess(args=['ffmpeg', '-y', '-loop', '1', '-i', 'imagefile.jpg', '-i', 'audiofile.mp3', '-c:v', 'libx264', '-tune', 'stillimage', '-c:a', 'aac', '-b:a', '192k', '-pix_fmt', 'yuv420p', '-shortest', 'output.mp4'], returncode=0)

In [1]:
import boto3
from moviepy.editor import ImageClip, AudioFileClip

# Initialize boto3 client
s3 = boto3.client(
    's3',
    aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",
    aws_secret_access_key="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",
    region_name='eu-west-1'
)

# Define S3 paths and local filenames
s3_audio_bucket = 'soulchain-dev1-output-video'
s3_audio_key = 'generated_videos/video_user_imane/audio1'
s3_image_bucket = 'soulchain-dev1-output-video'
s3_image_key = 'datalake_media/image--_S3mOGFzRU.jpg-c7ac1cb5-4639-4c50-b9a4-31cf8ececb51'
local_audio_path = 'audiofile.mp3'
local_image_path = 'imagefile.jpg'
output_video_path = 'output.mp4'

# Function to download file from S3
def download_file(bucket, key, local_path):
    s3.download_file(bucket, key, local_path)

# Download the audio and image files from S3
download_file(s3_audio_bucket, s3_audio_key, local_audio_path)
download_file(s3_image_bucket, s3_image_key, local_image_path)

# Create video using moviepy
audio_clip = AudioFileClip(local_audio_path)
image_clip = ImageClip(local_image_path).set_duration(audio_clip.duration)
video_clip = image_clip.set_audio(audio_clip)

# Write the result to a file
video_clip.write_videofile(output_video_path, fps=24, audio_codec='aac')

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Moviepy - Building video output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp4

MoviePy - Done.
Moviepy - Writing video output.mp4

Moviepy - Done !
Moviepy - video ready output.mp4

In [9]:
import json
from botocore.exceptions import ClientError
from moviepy.editor import VideoFileClip, ImageClip, AudioFileClip, CompositeVideoClip,concatenate_videoclips
import tempfile
from io import BytesIO
from PIL import Image
import numpy as np
import requests
import uuid
import os
from datalake import put_image_in_s3
from text import create_text_updated_clip,def_translation
from langdetect import detect
from text import get_argos
import base64
import tempfile



def get_first_word_after_slash(input_string):
    parts = input_string.split('/')
    
    last_part = parts[-1]
    
    sub_parts = last_part.split('-')
    
    first_word = sub_parts[0]
    
    return first_word


def change_media_path(s3,sub,final_keys,video_id, final_video_width, final_video_height,animation, position='bottom',fontsize=34,font_name="Arial-Bold",color='white',bg_color='black'):
    all_parts_keys=[]
    try:
        response = s3.get_object(Bucket='soulchain-dev1-output-video', Key='video_info.json')

        data = json.loads(response['Body'].read())
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            data = []
        else:
            raise
    video = next((v for v in data if v["video_id"] == video_id), None)

    all_keys = []
    if video and "video_parts" in video:
        all_keys = [part['key'] for part in video['video_parts']]

    if final_keys=="all":
        final_keys= all_keys


    if video:
        for final_key in final_keys:
            all_parts_keys.append(f"generated_videos/{video_id}/{video_id}_part_{final_key}.mp4")
            part = next((p for p in video["video_parts"] if p["key"] == final_key), None)
            if part:
                indx=final_key

                try:
                    response_audio = s3.get_object(Bucket='soulchain-dev1-output-video', Key=part["audio_key"])
                    audio_data = response_audio['Body'].read()
                except Exception as e:
                    print("Error reading audio from S3:", e)

                with tempfile.NamedTemporaryFile(suffix='.mp3') as temp_file:
                    temp_file.write(audio_data)
                    temp_file.seek(0)  
                    
                    audio = AudioFileClip(temp_file.name)
                    if part:
                       part["duration"] = audio.duration
                try:
                    media_list=[]
                    for media_key in part['media_key']:
                        response_image = s3.get_object(Bucket='soulchain-dev1-output-video', Key=media_key)
                        media_data = response_image['Body'].read()
                        print(media_data)
                        media_list.append(media_data)
                        
                            
                except Exception as e:
                    media_data=[]
                    
                media_data=media_list

                video_type= video["video_type"]


                if video_type=="mix":
                    video_type=get_first_word_after_slash(part['media_key'])

                if video_type=='image':
                    media_clips=[]
                    for media in media_data:
                        l=len(media_data)
                        image_stream = BytesIO(media)
                        image = Image.open(image_stream)
                        image = Image.open(image_stream).convert("RGB")
                        image_np = np.array(image)

                        media_clip = ImageClip(image_np, duration=((audio.duration)/l))
                        media_clip = media_clip.resize((final_video_width, final_video_height))

                        print("animating video")

                        if animation== "True":
                            media_clip = media_clip.resize(lambda t: (final_video_width * (1 + t/10), final_video_height * (1 + t/10)))
                            media_clip = media_clip.set_position(lambda t: ('center', t * 10 + 50))
                            target_width, target_height = final_video_width, final_video_height
                            media_clip = media_clip.resize(lambda t: (
                                int(target_width * (1 + t / 20)),
                                int(target_height * (1 + t / 20))
                            ))

                        media_clips.append(media_clip)
                    
                    media_clip=concatenate_videoclips(media_clips, method="compose")

                if video_type=='video':
                    media_clips=[]
                    for media in media_data:

                        l=len(media_data)
                        with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                            temp_file.write(media)
                            temp_file.seek(0)
                            video_clip = VideoFileClip(temp_file.name)
                            video_clip=video_clip.subclip(4, 10)
                            media_clip = video_clip.subclip(0, (audio.duration)/l)
                            media_clip = media_clip.resize((final_video_width, final_video_height))

                        media_clips.append(media_clip)
                    media_clip=concatenate_videoclips(media_clips, method="compose")

                
                media_clip = media_clip.set_audio(audio)

                if sub=='True':
                    text_clip = create_text_updated_clip(part["subtitles"], media_clip, audio.duration,position,fontsize,font_name,color,bg_color)
                    text_clip = text_clip.set_position(position)

                    final_clip = CompositeVideoClip([media_clip, text_clip])

                if sub=='False':
                    final_clip=media_clip

                with tempfile.NamedTemporaryFile(suffix='.mp4') as temp_output_file:
                    temp_output_file_path = temp_output_file.name
                    final_clip.write_videofile(temp_output_file_path, fps=24,audio_codec='aac')


                    try:
                        s3.upload_file(temp_output_file_path, 'soulchain-dev1-output-video',part["video_part_key"])

                    except Exception as e:
                                print("Error uploading final video to S3:", e)

            else:
                print(f"Part with key {final_key} not found.")

            user_id=video["user_id"]

            file_name = "example.txt"
            file_content = f'video part generated for part {indx}'
            with open(file_name, 'w') as file:
                file.write(file_content)

            s3.upload_file(file_name, 'soulchain-dev1-output-video', f"text_info/{user_id}/example.txt")
    else:
        print(f"Video with ID {video_id} not found.")

    data = json.dumps(data)
        
    s3.put_object(Bucket='soulchain-dev1-output-video', Key=f"video_info.json", Body=data)

    return all_parts_keys

In [11]:
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEM4YQVOSA",aws_secret_access_key="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", region_name='eu-west-1')
change_media_path(s3,"False","all","video_user1_7b88783c-75a7-46a8-bef5-3d7b586979c3", 1920, 1080,"False")

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x05\x03\x04\x04\x04\x03\x05\x04\x04\x04\x05\x05\x05\x06\x07\x0c\x08\x07\x07\x07\x07\x0f\x0b\x0b\t\x0c\x11\x0f\x12\x12\x11\x0f\x11\x11\x13\x16\x1c\x17\x13\x14\x1a\x15\x11\x11\x18!\x18\x1a\x1d\x1d\x1f\x1f\x1f\x13\x17"$"\x1e$\x1c\x1e\x1f\x1e\xff\xdb\x00C\x01\x05\x05\x05\x07\x06\x07\x0e\x08\x08\x0e\x1e\x14\x11\x14\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\xff\xc2\x00\x11\x08\x03\x19\x05\x00\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x00\x03\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\xff\xc4\x00\x19\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xda\x00\x0c\x03\x01\x00\x02\x10\x03\x10\x00\x00\x01\xfaZ\xd6\xbd\xff\x007\x1b\xd2\xa5\xcd\xe8Bb[2F\xcb\t7\x9cU\x9a(,\xa9\x0b\x18\x98T\xb9i\xcb)\xcdJ0\x81\xb1D\xd9%"SBB\xb0\x12\xb1\xa4\x91\x88Z 4x\x86\xef\x9c\x8e\x9a\xe5gK\xe6k\xd0\xb2\xa9i:\x8c\x97Hr\xae\xc5\\\x8b\xaeNca14VAH\x92\x90\x9b\x01\xa67.Zr-9\x06 \x10\x81\x02$\xd5\x88s`\x92)IB\x04J\xd9\x92\xe8\xa3\x99\xf4\xd4\xbc\xb5\xd2\xe3\x9e\xb7K\x9dP\xaa\xa6cS\x15[,\x11\xbc\xe0&\xab\'e\x90\x14\x9b%h\x19\x1a\x86f\x81\x93\xb2\xc8-\xcb\x99a\x0b@\xc9hVKf`\xf7\x0c^\xa4d\xf5\x177m%\x81O6j\xf0r\xee\xf0\r\xccE\xe93\x95\xdar\x94\xd5f\x8b\x99,d\xbb\x188ER\xc1\xb5\xc79\xd7R\xf1\xd7eK\xc7]B\xe0\xf5\x918\x83c\x9a,\xeb\x9e8\xae\xd9\xe1I\xd9\x1c\xc8\xe8\x8cU\x9bFN\xe7I\x1d#K\x8cN\xbd%\xe1\xafCI\xaf:\xfd*\xcd\xf3\xb4\xee%\xe5\xbdsZ\xbe|\x8e\xd3\xcd\x84\xf4\xe7\xc9\x8dOW?5\\\xfa\x11\xc4\xeb\xa62\xa4i\xd5f\xf4q\x9d]\x19\xbd\x1c\xb9\xbdIr6\x0c\x8dR\xe6T\xa0J\xaa\x95)S+R\x94\tj@\x1d\x10j\xcc\xde\xce\\\xabZ\x97\'\xa3\x977\xa3\x97\'\xa316U\x89\xaaL\x96\xa8\xc9h\xac\xcc\xb5d\x8d\x03\x94[\xc9\x1b,\x1ajf\xed\xa0p\x9bb)\xc4-Z\xe2\xba\x03\x99u$\xe7{\x15\x8b\xb4IHC\t( \xd03z\x06o@\x8a\xb7,:k-\xb8C\x0c\x9f`\xbc\x95\xd4/3\xdc\x8c\x9e\x92\x15\x12o\\\x92w\x1e|\x1e\x91\xe5\xcd\x9e\x9c\xf9\xaa\xce\xf8\xe2,\xe9\x8c]\x95\r\xd9\x9a\xd9\x98\x1d\x15/+\xea\xa8\xe4\xae\xba\x97\x8d\xf65\xe4\xd3\xa5\xcb\xcd\xa6\xa4M\xa1n\xb1R\xf4.d\x9d3\xcf5\xbey\x968j\xe6U\x15\x054\xcdl\xcc\x1e\xce\\kP\x87MUK\x8b\xac\x94\xbb\xbett\xaey:\x97,\xd9\xd6\xb9&\xba\xe7\x91\'Ts\xab7\x9c\x95\x9aJt\x8a\xa8\xcd\xebF/w.5\xb3\x97\x1a\xd9\xc6OW5\x95h\xcc\xdd\x92\xcbSf\x8f\x9f3\xadqM\x9d\xb3\xc56v\xc7)gD\xe3E\xa9t\x03D\xddK&\x9aK\x83\xe8\xb3\x96\xba\x9c\xbc\xd5\xb2\x96\x1b\x82\xcc\xe2\xb7\x9et\x9d\x11\xce\xac\xdervRLJ\xc2\x16\x81\x9b\xd2\x8c^\xb4a[\xd4\xbc\xf7\xbdK\x85\xecK\x9b\xb0\x96\n\t%)\x93C\x15T\xa1\xd8\xe5\xab\x10\xd9\x0b@\xcc\xd1$\x16\x89)Ri\x16B5x#\xa5s\x91\xd2s:\xe8xT\xba\xbc\xea)\x975\x0e\xc2]\x12\xa6!\x92\x92\xd6S[\xaeh\xb3\xaey\x12u.UgL\xf3\xb3U\x05P\x006\x92\xddK%\xb9`\xd1\x90ZT$\x94f\xabC\x14\x9a,\xd5Z\x91\x1a\x0b\x00\x07QR\xba\x96\xb4\xe5\xc5T8\xba\xcd\xcdh\xe2\xa5aD\x96\x89\x1a\x12&\x9c\x8a\xc5\x14\xae`\xb4\x92RP\x18\x03\x13tM2WRKo \xd4\xc5\x1b\xceA\xa2\x87`\x08\x10\x91\x92\xaa\xdeA\xa9\x90j\xb3\r\x08e\xbc\xea-\xc0\xba<\x89vx\x86\xc6l\xb54%ms[\t\x89\xa8d\xeaA\xc4\xd9\xaa\xc8(\x95e\x90[Hq\x0bWf+w\x18\x1b3\x05\xd0\xeb\x94\xebq\xc8\xfa\xda\xf2\xd7B\x8c\xdd\x8a9F\xaf\t:NTu.Q:\'\x10\xd2d\xa5:4\xc4\xdc9\xdf@s\xbd\xc3\x1a\xd1*a\x14H\xb6f\x1a<\x91\xb1\xce\x93\xa5r\xc9\xd6\xb8\xd5\x9dS\xccY\xb4\xe6\xc7,\xb2\x0b\x08t\xe5\xcc\xd5\x98\xbd\xa8\xe7}4s\xbe\x9a\xcd\xe6}my\xebw.7jQ\xc4\x9b>iN\xa5\xc95\xd8\xb8\xd5\x9dS\xc8\'Ls\x95\xbc\xe4Y\xa4\xa64\xe8\x97l\x83J\x97\x1a\xd8\x97\'\xab2z\x12\xc9h\x05+\xa1\x94\'J\xe5U\xd7<\x89:\xa3\x9dY\xbc\xe6U$\xd1\x15FOZ\\\x1e\xf5\x1c\xf5\xd2\xe3\x99\xf55\xe6\xae\x82\\\xaa\x92\xd3\xc6\x0e\xb3\x8aS\xbc\xf3\xa4\xf4W\x9d6z3\xe7\x95\xdd<\x81\xd18\xb4\xb4\x9d\x88\xa6A\xa5\x1b9SZ\x19(\xd8\xc1V\xeb\x10\xd9d\x1a\x19\xa4\xd5f\xcb!\x1a\x10U\x03\x84\xad\x99\xbd\x05\x83Ff\xedBb\x18\x92\xd12\x96\xa4\x04\xc1*)\r\r$RJ\xc6H1\x00\x98%BC\xa0\x92\x82\x1d\x86f\xac\xc4\xdc\x97\x17\xb0d\xf4fuD&\xe5\xab \x8b3\x9b4P\x8bPYj\x11r\x9d\x89S3[\x06\x07@s\xbd\xc3\x13r1\xad\x05\x82\xd9#\x06\xe0\x96\xdeA\xaa\xc8MT\x0bR\xd2)\xd0\xac\x96\xe1\x82\xe8\x13\x07\xb0\xb9;@\xd24x\xa3\xa5\xf2\xa9z\xceA;\x0e1z\xd70tNN\xca\x8b\xa9p\x9e\xa7g\x19\xda\xe3\x84\xef+\x85\xf6\xa8\xe4\xad\xd5\xb9:\x94\x1c"\xcc\x95\x9b\x19)w0+w\xce\'C\xe7%\xd8\xc1\xeah\xa0)\x0cJ\xd9\x06\xae\\\x9e\xcc\xc9\xea\xe3*\xd5\xcb\x93\xd0X-\x08\x01\x89\x14\x92(\x94\x94\x901\x14\xdc\x05\xa9"\x92b\x1b!\xd0J\xb9\xa0\x10\xc5%\x99\xcaj\xb2U\xb1\x82M\xcc\x12\xf4,\x04\xddb\xcdL\x99d\x83c\x84\xdbYt\xc84"\x0b\x16\x0b\x08Z$\x86*d#C\x14\x9a\xac\xca\xd1C\x185M\xb1\x14\xe2*\xdcfj\xd7#arv\x10\xc9Jy\xc9\xb1\x84\x9d+\x9aW\xaay\x92uO:^\x89\xc84QH*\xaa\xc0\xe8\xbb\x9eZ\xeaq\xcb]"\xe0\xf7q\x85j.uD\xb3B(\xceke\x8aM\x96H\xd1Ac\x90\x04\x14\x08@\x18*d\x1aTdl\xd7\x07\xb8`t8\xc5\xc9\xb5VdiX\xb8\xd6\xb0f\xc6n[J\x95\x14\xcc\xd6\xc1\x91\xa8fXKh\x01\x00\x08!\x89P\xb2\xa8ImRi\x0c\x94R\x94\x96@Q.\x84\xc1*D\x8c@B\xb14`+\x19\x03\x1c*\x05\x1c\x91D\x95O4hd\x1a,\xc2\xd4\xab)&\x08\x00`\x86\xc9-\x99=\x033W\x18\xbd\n\x86\xe6(\xceku\xcf\'B\xe7,\xdas\n\x96\xd33j\xac\x1e\xf5\x9b\xcc\xfa\x89y_R^z\xd8L\xea\x91N\x05\xd6\xb9\x91\xd4r#\xb2y\x03\xa9s;7\x9c\x99\xa2\x90b\x00\x02U\xb3%\xbb\xaec\xad\xc7!\xd6\xceG\xd2\xceg\xbb\x8ckD\xb3@:\xcd\x1b>tt\x9c\xa8\xeb9\x11\xd6r\x87J\xe7e6\xecM\xd2\xc3\xb7,;k\x9b\xd1D\x16\x84\xd2\x19\n\xcd\x0c\x95\x9a\x99\x06\xa6D\xba\x19\x96hA\r\x0cC\x044\x00\xa8\x10\x8d!\\\x89\x04\xd5 \x11*d-Y\x8dj\xcc\xdd\xa9F\x91d\x05\x12\xc6*\x96Kd\x1a\x04;R\xc8\xd5!\xa4C@\xe5%\x99\xcdns\xa3\xa8\xe3Gj\xe3\x0e\xb3\x95\x9d\x0b&X\x80T\xc8\x9dY\x89\xb8`\xf7#\x17\xa0@\xe6\x9b\xce\r\x96\n\xcd\x96"k2\xe8\x1b\x96\r)17\x0cM\xda\xe2\xf6%\xce\xad\xc4S\x154\x14@Y\x98h\xa1\x94\x80\x15\x84+D\x8dX\x81\x00\x98&\x12\xb4i\x92\xe8k\xce\xfah\xe5\xae\x87/;\xdd\x19\xbbJ\t\x1a\x18\t\xd0\xf2K\xb9\x82:W4\x9dK\x94\xb3\xa2p,\xd6`)"\xc0\x01\x89\x81D\xa8\xa0E8\x92\x9a\xc1a\x05\t#Bi\x14\x92(\x94Y\x05S\x82,\x961\xb5\x92\xc8\x87eC\xa5\x05B]^2t\x1c\xc2t.ttN\n\xcd\xa7%f\xab&Z\x86\x8d\x14L\xebF\x0b\xa6\x97\x8d\xf6\x07#\xebK\xcf\xa5\x90\x9c\xa3G\x88l`\x8e\x83\x99\'K\xe4\x85\xed\\J\xce\xc5\xc8\xcd\xe71-K\xa2t\x0c\xde\xa1\x93\xd4L\xea\xdc\xb2Y5&\x94d\xf5\xa8\xc1\xf4\x0b\x8b\xd8\x977H\t\x93S\x9dY\xd2rI\xdap\x87j\xe2U\xda\xb8\x84\xeb\x9eWf\xeb*\x1b\x1a\xa2\xaa \xd5\x99=Y\x95h\xa5\x9a\x10\xdeaj\x02\x90\xc8\x9d\x1d\x99-\xc3#Ast\x91\xcc\x962\x15Q\x08\xb2\x02\xc8e\x03A\xbaT\xe9\xca\xa8%\xa2Q\xa1\x9a\x8dLUm9#I\x92\xc2[IT\x12S \xb0\x9amU"\x1b\x94hf\x97E\r\x1c\xb6J\xd03z\x04\x16\x89\x1a\x10\xc1*d\x94\x84\xd0S\xc9&\xa6Iu2Vjd\x1a\x98\xb3U\x934R\x14\xe0)"\x9a\x14%e\x99\x9a\x06OR2z\x86oF\xb9;d\x1a9s5fU\xa1\x11LWY#w\xcb\'b\xe3\x0e\xb9\xe6\x13i\xcc\xb1\xcbu\x9a\xd4LM\x99\x81\xd1K\xca\xfaY\xcc\xfa\x9c\xbc\xc7I.5r:\xcaN\x83\x99\x1dG)]\'3\x8d\xcc\x04\xd8\xc0\xad\xd6(\xd8\xc460\r\x8c\x03u\x90\x9aJtM\xd1\x91\xb5K\xccu4\xe3ZV\xa6F\xf4\xbc\xf5\xd2\xe5\xe7\xad\xea0\xadIa\xd3Y\x18A\xa0bl\x8cMf\xc8\x1cYDI\xaa\xc8\x97S$ja6t\xcf9f\xeb&Y4\x89]\xcb\x91\xd1R\xf3WE/3\xe9q\xce\xf6#*\xb4\xb2\xd2\xaa3\x93e\x82N\x85\xcc\xac\xe9\\\xc2tN.\xb4\x94\xc4S \xd1\x12\xe8\x89*\x884\x177\xa32z\x11\x9b\xa0\x95L\x85\xa1Y\x9a"\n@\xe5\x16f\x16\xa0J%\x14IT\x86"\xdcfkK\x81\xd0\xe3\x98\xebk\xc8\xfa\x83\x9a\xb7\x93#U\x10Z\xa9)\x12\xc4\x8c\x95Vd\x8dV*\xcdg4Y\x9b\xb2\x92`U\x19\xd5\xd4\xb9=\x89q\xadQ\x0e\xc2K"[d\x8d-\x11&\xc6\x12t\x9c\xaa\xce\xa3\x95\x1dK\x99\x9b\xac\x1ajd\xab\xbd\xc3\xce\xe9\xc9\x14\xe0[ (\x90\xa4\x95\x8d)\xa7*Y\xa9SB\x15\x89XA\xa3\x8c\x8d\x9c\xb8\x1d,\xe6}L\xe6\xae\x92\\kQa\xb5\x03\x94Y\x92\xad\x0c\x92i0YP\x04\xad\x04\xc4\xd8\xacV\xe1\x8b\xd5\x19\xbd\x02\x1d2Jr\xc3\xba2\xabr\xc3\xa4\x0eB\x94\x85\x10\x8d\x16i4Y\x95\xa4\xe6Y\xa2\x80sL\xcdl\xcc\x0e\x97\x1c\xaf\xa9\x9c\xd7\xbb\x9a\xc2\xf4\tl\x96\x9eh\xd9\xf3I\xd6qM\x9d\xd3\xc2\x8e\xe9\xe3Vu\xaeEgZ\xe5\x0e\x95\xcc\xcd\xe7&Y,\nfkf\x9c\xe7K9\x9fS\x9a\xe6},\xe7\xad\x9ceZ)S\x12\xb7\x9c\x9a\xac\xa6\xcd\x96)6X\xaa\xd8\xc1&\xf3\x89ZJ\x04\xad\xa6f\xads4\x084\x08)\x90h\xcc\x8dY\x8b\xd8\x8fA\xf9\xf9\xe7\xa7\xa8\xbc\xb1}%\xe6\x92\xf7\xcf\x10\x9d1\x8c\xeam\x19\x976\xa4\xb1\xaai\x0f[\xack{\xcd\xe7}7/%u\xb9yk\xa4\x97\x9d\xee\x18\xad\xa4\xcdk$\x84\x96d\xabc\x9d\'I\xc8\x8e\xb9\xe5VuO0\x9d\x0b\x05[,\xc2\xe4u%\xdc\x98\x9b\xb5\xc1\xee\xe5\xc2\xb4\x08-\x12PJ\xb0\x95\xa2$`\x81#\x12Z!Y\xa2\xcd\x1b\x18#\xa0\xe5\x0e\xa7\xc4\x93\xb9\xf0\xa3\xb9q5\xeb\\\xcd7\x98\xaa\x15\xd4b\xbaZ\xf2\xbe\xba\x8e\x13\xd0\x0f=\xfa\x08\xe1\xae\xa4\xbc\xefID\xe6MLf\xba\x0e`\xe9\\\xe1\xb1\x90jf&\x84\x0bNh\x1ap\x08\xa6\x80J\xe8\xc5t8\xe5}Es\x1d!\x83\xd1\x10\xc42\x11\xa1\x9252,\xd5f\x1a(\r\x08\x16\xdeBj\xf2r\xe8\xa2\x86\xa9\x99\x9b3\x88\xd0\xd4\x87nXzQ\x93\xda\xa5\xe7\xad\x99\x95hB\xa4\xd6\xab2]k\x00\xe8|\xc4t\xaevl\xb3\x16\xd4\xab\x1aRT\xcc\xd9s3e\xcc\xcd\x96\xa5%)`\xaa\x8cM\xe8\xe6:\xaa^W\xd6\x18V\xe4\xd6UDKrQ2hf\x8dV*\xcd\x96H\xd1fYJR4\x95\x08V!\xb4\x85\xab\\^\xf5\x1c\xaf\xad\xaf+\xebr\xf2\xdfC\x8ez\xdc\\kD\x15\x9c\xcb\xd1\\Pz\x0b\xce\x8b=E\xe5\xa3\xd2\x9f8\xb3\xb6yIw\x8c\xdd\x95-\x90\xa3\xa0\xc5oVs\xbd\xd9\x83\xd9\x99=\x19\x0e\xc9f\x99\x0e\xb3\x17W\x82:W0\x9d+\x9c7X\xba\xd0\xcd\x1a\xac\xd1\xa4K\xb1*f&\xcc\xc1t\x87;\xe8%\xc0\xd4\xb2\x1d!\x0010\x00bR\xdb\xcd&\xcf\x11w2\xa2\xd2\xa5KB9\xde\x97\xa9\x8b\xde\xa5\xe7}.9\xab\xa5\xaf5nK\x8dR\x1b\xcaN\x97\xc7\x9az\x0b\xce\x9b=\x19\xf3\x95w\xe7\xc8\xd3|\xe1\xd16\x19-\xaa\xceg\xd2\xe3\x9d\xf45\xe7\xad\xdca[\x12\xe4\xf4\x08t\x12\xc1Y(\xb5\x02\\\xca-B\xb2\xcc\xd2h\xb2\x9a\xdda\'B\xe7\r\xd6%\x9bNa\xa9\x934I\x8c\x1a\rT\xb2\xdbYV$\x94\xd6]\x10\x8a\x16JBT\x10\xac\xb2\n\x04\x08\xa7\x927X\xa3u\x80m9\xa4\xd5f\x1f)\xf3?k\xf0\xdc=>\xc7\xd5~=<\xba\xfe\xee\xff\x001\xfb\x8fG\x9b\xd7|\xfbt\xe5o6\xb6&\xa0RKn%\xb0n\x12\xea\xf9\xf3\xb3\xa8\xe4\xa8\xe8\x9cE\xd5f\x16fY\xa1\x93M\x14\x15jX\xc0\x95+\xa4\xcc\xda\x97\x07\xd1Q\xcb]-y\xab\xa0\x8ckAf\x92Zy\xa4\xd0\xc84\x9c\xd2i0Ws\xe6&\xba\x0et\x9b\xacUk0#\x90\xa12\xc40\x1c\x85\x99\x91d2\x80P(\x92\x9cKiJ\x90\xb2\x14hd\x1a\xbcCS$l\xb1Vl\xb1F\xcb\x19\xb3i\xc9&\x93\x05T\xa4\x8d\x02\x82h\x03\x11Me\xd3&\x9d\x12\xea\xa5\xcd\xebQ\x89\xbb\x97\n\xdc\\\x1e\xc8\xcd\xd4\x812i9\xc5\x9b,\x15l\xb1Q\xaa\xcc4P\xd5\xa4\x91\xa6\xe5\x92\x95 \xa8\x92\xc5\x89\xd0L\x9e\xae\xce\x7f\x83\xfd\x0f\xf3\x8e}>;\x1b\x8f\x1f\xb8\xf4|\xd6}w\xd6\xfeO\xd5\xbe\x7f\xba\x9f\x9e}\xd7\xa7\xcd\xd4\xf3:r\xd0\xcd\x1a,\xcb.Q)4\xaaF\xae[\x96\x94\xe4Zr\xc6*$\xba\x97\'\xab2\xad\x1c\xb2\xe9\xca\x98\xc0\x08\x13\x04\xc2\x81"\xcc\xd1\xa1\x8c\xd9\xba\xc45\x9c\xda4\xcaJ\xe8\xd8\xc6f\xba\x17<\x9dG*^\xa5\xcc\xe3u\x90\\\xa0\x12\x9df\xd1D\x1aU\x98\xd6\xf5/9\xd1Q\xcd[\x86&\xe9rz\x91\x99h\x90\x82\xcc\xa2\xb6X\x86\x8b4Z\x90\x15\x12\xca\xba2\x9d\xa1 \xb5\xa9\x03w2\xf4\xb8\xc2\xba(\xe6}D\xb8V\xc2\xc3\xa5+y\x89\xa3\xc2W\xa6y\x95\x9d3\xcc\xac\xdeqI\xac\xc1eJj\x01)J\xa5L\xa5\x85\xb3\x8c\x1e\xee\xb9\xebb1\xad\n\x96$\xaa\xc9\x1b\xd72;\x1f\x04\xc7\xa4ypz\xdc\x9eO\xe5\\\xfb{?(m\xe3\xfa9\x1d[q\xf6y3\xec;\x8f\x1b^\xdc\xf5\xc3/o\xe7\x9fN?\xa8}\'\xe2\xdfK\xdb\xcf\xfaC\xe4\xee\xf4\xf9a\xe9ve=\x01\xcf[\x96d\xf4Bh(\x85\x1a\x99\x15\xb1\x88l\xf0#\xa1`/B\xc05Y\x96h\xa6\xa0)\xac:d\x16\x10\xe9\x12PK`\x86\x86$Y\x9c\x9b,P\xc7SriQ\x81\xd5U\xc8\xfb\x1cq\xd7Z\xb3\x9e\xf4\t\xa4\x8by#c\x9d\x1d\x07,\xd9\xd7<\xb0\x9d\xb3\xc4\x8e\xb9\xe6,\xdas\x17B^t\xc1J\xc4\xd6\xa5\x92\xe6jY\x91\xb0\x99\xbd\x0b25W1T\x87y\xc9\xd0s\x07R\xe4\x0e\xa5\xce&\xf3\x9b*YIS3Z+3Z"\'Tfh&e\xa0i\x1a<E\xd9\xf3\x86\xeb\x10\xd5f\x93E,i\xb2\riy\xce\xaa\x8e7\xda\xd7\x84\xf4\x1c\xbey\xe8\x87\x9d]\xee<\xf5\xe8|\xda\xfcg\xc6\xed\x8f\x87\xe8\xe9\xd7\xc9\xd9\xe7\xf7\xde\x98\xcf/_f\xfc=\x9c\xba\xf6\xa3\xdb\xf1\xf6\xf9._\xd7w\xf5\xfc\xcf\xc59\xff\x00f\xf8\x1fW\x97\x9b\xf5/\xc9=_O\x97\xf5#\x87\x7f\xa1\xf3\xb7X\x89\xa2\x9a\xb1-4\x97\x9c\xea\xb3\x8a\xbbn^\x07\xe8R\xf9\xcf\xd2q\xe6\xbfL_:\xbb\xa69\xae\xb3]_6vv\xaf=\x1d\xf3\xc2\x97\xae9\x84\xe8\x9c\x92\xe8\xa1Yd\x85\t\x80\xe8\xcc\xd2\x8c\x1fE\'1\xd7r\xe6s\x9b\xcfJ\xc5\xcb\xa2TJ\xd1\x98\x9b\x86\x0b\xa5\x9c\xa7S9\x1fY\x1c\xa7R9\xabYY\t)D\xa6\x8a\x05\xb9D\xa2h@\xacd\x96S\x90\xa4RI\xa5\x18\x9d\x0c\xe6\xae\x87\x1c\xf5\xb1./UP\xd9\t\x89Y%\x94\xa1\x16c6o8\xc9\xba\xc44P\r\n\xc6\x93@\x1c\xd4\x95Ff\xb6`\xfa,\xe5}n9k\xa9\xcb\xcd[\xb5\xc6\xb4K,\x94\xb7\x92\x97c\x9el\xe99$\xeb\x9e9\xb9\xed\xcf\x8c:\xbe\x03\xec\xff\x00\'\xe5\xdf\xc5 \xf1\xfbz\xf6\xe6\xdf\x8f\xb3T\xd6=GL\xfa\x1c{_\xd1y\xbe\xa7\xcc\xf6}\xe7\xbd\xf1\x7f]\xd3\xe7|\x1f\xe4\xff\x00\xd3\xbf\x05\xf4x|o\xaf\xf1\xdfE\'\x17\xd8yYz|\xdfo\x7f\r\xef{\xbe\x7f\xbd|\xf7\xd7\x8fC\xe4I\xd8\xb8\xe6\xbb\xa7\x8al\xed\x8eEgL`%\xca,Sn\xb34q\x91\xad\x18\x1dMy_[\x97\x91\xf5\xb3\x91\xf5#\n\xd2aTEns#\xa8\xe3\x0e\xc9\xe5\x13\xa9s\xd1\xa1,\xb3F\xb9\x9a\x8b\x9b\xb0\x8ad&\xa6\xadB.eXM+3\x9dC"\xc9a\xd2%[Hv\xc8v\xc8vK4\x03p\x8d^,\xd5f\x8d\x0c\xd9jTZ\x85V\xa5%\xa8UFsf\x93\x01R\x99%\x91.\xdc\xb9\x9bR\xe0\xf7\x0cM\x83\'i\x15\xc3\xadk\x9c\x97\xa4\xe6q\xba\xc9\xd5\x92\xe0\x18H\xca\x95h\x82\xd1\x05\xa4\x89\xd4\xac\x96\xe1\xcct\x87!\xd7\'3\xdaS\x8f\xf1o\xda\xbf\x14\xf3\xfa\xf9\x9a~oN\x9b\xf2\xd6{o\xaf=\xe3\xbfWW\x99\xdb\xc7\xd3\xeaz\xbe.\xbe\x0fo\xd6\xfa\xff\x00\r\xee\xf2\xe7\xfa\x17\xa9\xf9\x8e\x9d\xfc\x9fw\xf9\xaf\xbf^\xbf7\xe4\xab\xee>3\xd7\xc3\xbe\xbc>\xa9\xbf\xa3\xf5\xfeC|\xeb\xef;?:\xbe\xfeo\xd2\x9f\xc5\xfdGo?eo]\xfc\xbc\xefwX\xbd\x08\x86\xe6\x9b\x85\x16e5\xb9\xce\x93\xa1`V\xcb0\xb44KW.&\xf4\xbc\xef\xa02z\x114%bE\xa8F\xc6)7\\\xebN\x89\xc06Y*\xd6sI\xaa\xc9\x1a\x99\x85\xa4\xe5@\xc4S\xb2\x1e\x8c\xcd\xea\xcc\xcd\x1cfh\x10\xe8\x95\r\x88md\xa2%R\x10\x95\x8dJ\xb1\xa4\x91\xa4\xe9\x88\x1aAD\x85\x12E9cM\xac\x94\xcc\xcdY\x8b\xd9\xcb\x8b\xd9\xc6/V\xb9\xbb\x04\xc2Zy\xc9\xba\xc2k\xa1s\xa4\xdeqVl\xb2\x93c\x08\xb3\xa4\xe5\x94\xeb\\\x8e\xba\'\x16ZU,\x1a4\xc5t3\x9c\xe9K\xe7~-\xfb\x87\xe2\xfe\x7fO\x00\x9f\x9b\xd4\x81\xab\xd7;\x9d::x\xb6\xe3\xea\xed\xef\xf2\xff\x00M\xc5\xf2\xfb\xbe\x9d\xfb\xfeO\x8d\xb7\xa8t\xe5\xc9\xd1K\xaf\x19*l\xacm/\x99\xe7}\x14\xe7\x7f%\xaf\xd3\xacu\xf11\xfa"_\x1f\xdd\xcdo\x95\xa9{\xe49kD\xb1*z\x92\xee\x93*\xd6\x8c\xabBX\xa6\xc4Q*\x1a\x18\x90\xc9\x9a\xd1g&\xcb\x19M\xcc\x03c\x9dY\xd0\xb0f\xa0\xa9\x92\x8b ,\x96\n\xe93z\xb5\xcd\xe8K4I\xa3\xc5GC\xe5U\xd4r\x91\xd2s\x15\xd2r\x91\xd2sMu.T\x9dQ\xce\x1b\xac\x8a\xd1f%\x90\xc6&\x00\xc0d"\x99\x06\x81\x9b\xd0\\\xdd\xb8\xcd\xe8\xd77l\x87NY`\x0eQfi5Y\xc9\xa9\x8c\xd6\xcb\t\xb3u\x8a\xb3e\x98\x9a\xa8\xa5\xa2X\x01\x03Hn\x15jd\xa3w\xce/A\xcc\'J\xe6\x0e\x83\x9c6\x9c\x82\xff\x00,\xfd?\xe6\xb1\xd3\xf2\xc5q\xe2\xfa\r\x04U\xe7SZm\xcf\xec\xcd\xfdO\xdb\xe4}\x0f\x95\xaa\xc8\xe9\xcfC:\x8a\x117N\x1c\xb6\xa5\xca\xd3*M*\xe3\x1a\xd6\x8c^\xec\xc6\xb4\x08\xa0(\x80\xd1\xe0\x8e\x83\x91\'Z\xe3U\xdb<L\xea\x9c\x19\xaa\x9a\x94T\xcc\xcd\x9a\xf3\x9d\x01\x81\xbc\xa6n\x909E\x90\xa5\xd5d\x8d\x1c.\x99\xd1\xe2\xe4\xd4\xcc[y\xb2\xc8\xab\x18\xdc\xb2\xe9\x90h\xe32\xc2\x0bU*\xc8\x83Dfl\x19-\x83\x13dd\xf4K,IO4\xbb<\x14n`\xab\xa0\xe7$\xe89\xca\xd8\xc5\x9a\xac\x83c\x16jf\x1a\x19\x06\x84\x05$\r0C\tTY\x99a\x05J7\x08\xd0\xcd\x1a\xac\x91\xac\xe6U\xa8"\xd4\x95d4\xa1T\xb2[35fOR\\\x8dC2\xe6\x81LT\xc4\x9f\x97\xfc\xcf\xeb_\x94y=\xf0\'\xcb\xb3s\xecf\xf6\xfe\xe1\xf2\xbfc\xe5\xf4|\xbd{>?\xda\xf8aOxT1\xd42\xdeB\xea\xb3e\xa8\x13B\x12\xd9\r)\xc5(\xa9\xa4\x9a%\x92\x90\x86\xa0\x05TI\x16f\xabS\x10\xd5\xe5x\xe8)E\xa9r\xb1%\xa4\x9a&1\r\x89[\xb33B\xc4\xf4z\xcc;AR\xa5\xd1\xe2&\xcb\x12\xb52\r\x0c\xc3C\x14\x9b\x98%\xe89\xaa]\x96D\xb6\xa5\x17)#IU\x92\x16\xa5\xca\xd3\t-\x99\x1b4\xc0\xe8u\xcav4\xe3}\x8c\xe4\xae\x84eNb\xcc\xa5z\x0edu.Q:g\x01v\x9c\x95\x9a\xac\x91\xaa\xcd\x94$Q\x99e\xa4#\x13\x11A&\x8c\xcdn\xd7\x03\xa1\x9c\xef\xa5F5iG2\x9a,\xa4\xd5f\xac\xd1J\x1aa\n\xc2\x16\x81\x92\xd6W?\xcc?R\xf9n}\x7f2T\xfc?B\xbe\xe7\xe2\xbe\x9b\x87\x7f\xd0=/\x8c\xf5\xbc~\xcf\xd3~K\xd6\xf5}\x9f?\xe2\x0e\x9eo\xaf\xf2FV\xb3%\xb4\xcd\xe8TS\x00\x08m0M\xac-\x1ad\xb7q\x81\xb9n5\xa1\x10\xe9\x03\x94\xb4\xa5%))\xa0\x00\x15\xb4Cr\x8b M\x0c\xda\xdb\xcc\x96\xc8E\xa9v\x03b6+#dd\xf4\x08,H(\xa9T\xa5I\x89#*JR\xa2\x904\r&\x82(\x92\x9dK\xa7\x13I\x16\xf3\x93g\xce/B\xe6#\xa2pI\xbc\xe2\xea\xeb\'\x9dhdK\xa9\x90\xba\xbc\xdc\xba\x99\x0bJ\x0b\x8a \xb2\xe5\x08\x01\xa8\xdc\x06\x8f!5\xac\x19\xb1\x8b53F\xaf\x14\xbb\xac\x11\xd0\xb0Q\xbc\xe6\xd6\x92R\xd1 \xc4P\xcc\xe3E\xc1\xe4\xe3\x7fM\xcf\xf2\x9c|\xfb}4|T\xf1\xed\xf78\xfc_9\xf7\x9e\x9f\xe6\xb4\x9f\xaa\x9f\x9c\xfa\x1dy}\xa6~o\xa9\xd7\x8f\xe3\xdeo\xe8_\x9fy}\x97\xd5\xc7\xd3\xcb\xb7\xb7\xeb\xfcg\xb3\xe7\xf4~\x91\xf6\xdf\x96\xfdw\x97\xd3\xf6\xdf\'\xed\xfa^\xdf\x9d\xf0\xec\xc3\xeb\xfc\x9d\x8c\xefY\xa4\xeaYv\xcc\xdd\x8b,E<\x91\xb3\xe7\x93\xa6y\x8b:\'\n)&2T\xb6\xa4(\x18\x86\x12R\xb1\x05"c\x9a\x15T\xb9\xad\xd9\x83\xe8\xa3\x9c\xeag3\xe9\x0cn\xd4\x15\tes\xce\xf3\xd383YNh\x07(\'\x00\xda\xa2\x9d\x99-\xdd\xcf9\xd4\x1c\xcf\xa89_B15\x92X\xacd\xa8\xa5\x05\x8c\x94R\x10\x02\x19!Hr\xa2\x96t&*(\x96\x16\xac\xc9\xdb\x9a\x96AO5s\xa2\xcc\xb9\xb5%\x84\xd1\xac\xc1BKb\x80J&\x12Qd\x8d\xa2(\x10\xd0\xdc\x858kG\x85\xe5\xf1\xef\xf5~O\xca\xf3\xf2\xef\xeb\xf8\x9d\xbc\x1c;y\xeb\xd2\xb9\xae\xdf:\xa367\xbe%r\xb2\xb9\xaeg\x80\x8c\xbb\xeb^\x89\xcf7\xdd\xf8\xdf[Mg\xc1\xd3^E\xd3\xb3\x8by\xaf\xa9\xf7~\x1b\xde\xf3z\x7fC\xfao\xcd=?/\xa3\xf4\x7f\x92\xfaK\xfa?/\xe6\x18}O\x984\x02bAe\x90h,\x14\xd32\xc33I$\xa5d\xab\x08)\x12\xe8%\xd0\xa3N\x1b\x1a\x94\x94[\xcd.\xcf\x04t\x1c\xec\xdasiH\x16U\xbb16\x0c\r\xc3\x01\x9a\xcb\x01[\x80\xb7\x99.\xa6A\xb3\xc1\x9b,\x83U\x9a4P\x0cB\x00\x12PJ\xb0\x82\xc2\x16\x8c\xcdj\xe5\xc4\xd8\\\x8d\tahD\x94,\x94\x10P\x924\t\xa0\x1aP\x00\x13\x10\xdc\xb0[35fN\xc2\nd-(\xc4\xd8L\r\xd1\x81\xd0/9\xba2Z\xe2W\x07\x85\xe0\xf1\xef\xebq\xf9:y\xbd=\x109\xbe\x87\xe7\xf1\x9e\xaf?\x0f\\a\xf6\xff\x003vq=\x88\xdf\x03\xcb\xab\xd7\xab0\xce\xeeY\xe0\xf4r_\x16=\xfe\x1b\x8c\xfd?\x0f\xa4\xee\xf3\xfd<\xcf\x0e}\xceJ^\xcf\xcfz\x1c\xfa}\x07\xa1\xf2\xff\x00C\xcb\xb7\xe9\xbfE\xf9\xdf\xd4\xf9;sq}\x1f\x8f\xf7\xbe\x0f+\xe8;r\xc0\xdaL\xcbD\x156K\x15\xc8\x9aT\xa9\xa4\x16\x12P!\x8a\xc9\x12\x9c\x8bBC\x13\x00!\xb4\r\xa1X\x00\xd01\x03\x104\xc1+\x0ew\xa3\xd6sz5\x87D\xa8\x00\x04\x8cT\xa8m$\xb7.oAst\x90r\x96\x8c\xc8\xd1f\x97S\x07.\xb3\x02\xda\xcdF\x8a\x11JhJ\x89d\xb1`\xb7fOKL\x17[^W\xd4\xa3\x98\xd9\x18\x9b\xe8\x9c\xd7\xac4$\x05\x10\x94B\x97g\xcb3]Y\xe5\x82v.\n;#7Nf\xf3\xac\xaay\x0e\xdd<//:\xf7\xbe3\xcf\xbe=\xf3}\xe67\x8dG4\xba\xe3>\x89\x8df\x8d\xf0\xe1\xe8N\x0fW\xd8\xf2is^+\x84m\xa4\x9b-\xb1^\x9c+\x03x\xd7\x8c\xec\xcfX\x88\xaa\x17\x83O[Z\xe3\xca\x12c\xe6\xfd6:\xcf\x9d\xeex\xfe\x967\xe8\xfd\xcf\xc2\xfd?\x93\xd9\xf7\xff\x00\x1d\xf5\x1f\x8c\xf6\xf1\xfe\x9d\x7f\x98\xfb\xbe\xff\x00\x1f\xd8\xd7\x91\xe8\xf4\xe5\xacl\xf7\x8ei\xe9\x8dg\x9dn\xaeq[*\xc9\xdaD\xd2\xb2\x9c\xd4\xa0\xdc\xb2S!\xd8ESY(\x11NX4\x08V\x84\x12Q\x9c\xd9\xb1\xcc\xa5\xe9\\\xd2uO:]\xe74v\xa6\xf5\x99-\xc6n\xd9\x06\x89a\xd3 \xa5*hV\xf2R\xea\xb3\xa8i\xcc\xa4\xdb\\MC:\xa8\x1aw./\\e+\x14tO=\'Mq){\xf3\xe7\xa3M80=c\xc6\xcc\xf7\xdf\x8dg\xab>\\\x9e\xbe~e\xd9\xe8/5K\xe9W\x9f\xa1\xd9\x92\x94\xd3\x0f\x13\xce\xcfO{\x1f:s\xafL\xf3\x15\x9e\x86\x9cz\x1e\x8f\x9c\x91\xc1\x97\xa1\xaeu\xe5uv\xdd\x89O\x90wy\xde\\c\xa9\xcdZ\xe3u|[\xe6\xef\xc3\xca\xcd%\xeeuy\x99\xb2z\xfaX\xf9\xb1\xe7=^\x7f<=.=:\x0e_S\x8a\xcbS\xbc\xb3\xcf\xa6i\xeapVf\xbc\xdbB\xd362\xd2\xda\xab\xad\xac\xe2\xbd0\xb9\xef\xcf\x1e\xab7\xfa\xdf\x92\xfb\x1f\x0f\xbf\xda\xfcw\xf4\x9f\xcd\xe7?J\xf1\xf5\xbd\xde>\x7fC\xc9\xdb\xa6>\xa3\xa3\xc1\xf4z\xf1\xf5\xb5\xf3cS\xd7\x9e\x1d\xee5To\x12\x9c\xef\x08e\x89\xd0&\x91\xa3\xc6c\xa0\xe6k\xd2\xb9\x94\xbd+\x9c]\xa6\x02\x94\x12\xd1.\x04\xd2\x89\x96!\x80\xa8\xa9lD6z\x13\x82\x9a\xd5\xc4\x1b,\x99M<\xe8\x9aB\xa1\x82\x965b\x8a&\x1d^\xb1\x8c\xeb\x0b\x81\xae2\xe8\xf9\xba\xa5\x9c\xf5\xce\xe7=\x1eK\xd2qY\xb7,\xe8F}\xd4y\xb4\xc9u\xaem\xd2r\xac\xea\xf7\xe0\xcb7~\'\xcc\xbe\xa7\x1e\n\xb9\xdd\x18\xd6\xbd^T\x1e\xd77\x99\x06\xbbqVu{qB\xfbYy\xbak=G$\xcb\xd9\xa7!\'\xb3\xc9\xc7\xd9\xa99\xf9\xdcX\xeb\xd7\xc1\xc7\xd1\xcf\xae\xf9k\xc9\x0f\x8azR\xf8\xf7*f:#\x05\xd2\xa6\xabND\x9ba\xa7|\xbe,}\x8f\x0e:\xfc\xff\x00N\xd8\xef\x95\x9c\xfaY\xad%.\xfas$\xdask\xb6\x9ctt\xbe\r&\xba;rX\xe8\xb4\xde\xb5\x98\xabA\x97\x9e\xf5\x8d\xb8b\xd3\xda\xfbo\x93\xf2\xfc\xde\x8b\xbe:\xb9\xf5z\xd7\xa3\xeb\xf3q\xef\xd3\xc1\xdb\x87?\xbd\xe4\xf6\x1e\x97F5\xbck\xb6-:_9f\xeb\x13Y\xd6S\xd4\x00@\x00\x02\x92sr\xda,bv1\x00\x85r\xdc\xb5`J\x86\x00\x84b`\x00\x00u\xaa\x9cu\xady\xe6^\x8a\xce#\xa61\xcc\xe8\xd7\xcd\xbb{\xd6\x17\x9b\xaeW\x84lp\xe2\xbe\xa5\xf9\x8ak\xbf\x1f;\x14\xf76\xf9\xac\x8f\xa7\xcb\xe7\xad}\xec\xbcQ=\x0c\xf1\x95\xeaO2\xd77<\xbd\xca\x1

MoviePy - Done.
Moviepy - Writing video /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmp9un6hiu2.mp4

Moviepy - Done !
Moviepy - video ready /var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/tmp9un6hiu2.mp4

['generated_videos/video_user1_7b88783c-75a7-46a8-bef5-3d7b586979c3/video_user1_7b88783c-75a7-46a8-bef5-3d7b586979c3_part_1.mp4']

In [1]:
pip show elevenlabs

Name: elevenlabs
Version: 0.2.27
Summary: The official elevenlabs python package.
Home-page: https://github.com/elevenlabs/elevenlabs-python
Author: Elevenlabs
Author-email:
License:
Location: /Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages
Requires: ipython, pydantic, requests, websockets
Required-by:
Note: you may need to restart the kernel to use updated packages.