In [21]:
import ollama
def get_model_response(prompt):
    response = ollama.generate(model='llama3',prompt=prompt,)
    return response['response']

def extract_main_topics(response):
    topics = [line.split('**')[1].strip() for line in response.split('\n') if line.startswith('1.') or line.startswith('2.') or line.startswith('3.')]
    return topics

prompt = "what are the 3 main topics in this text : A road in the middle of a snowy forest"
response = get_model_response(prompt)
print(response)

topics = extract_main_topics(response)
print(topics)

Based on the provided text, I would identify the three main topics as:

1. **Location**: The text describes a specific location - "a road in the middle of a snowy forest".
2. **Environment**: The text focuses on the environment of this location, specifically mentioning snow and a forest.
3. **Scene setting**: The text sets a scene, painting a picture of a serene and possibly peaceful or isolated atmosphere.
['Location', 'Environment', 'Scene setting']

In [22]:
import spacy
nlp = spacy.load("en_core_web_sm")


def extract_nouns(text):
    doc = nlp(text)
    keywords = [token.text for token in doc if token.pos_ == "NOUN" and token.text.lower()]
    return keywords

extract_nouns("A road in the middle of a snowy forest")

['road', 'middle', 'forest']

In [17]:
from topic import find_topics

find_topics("a road in the middle of a snowy forest")

,id,original_sentence,sentence,topic,terms,sentence_part_id
0,1,a road in the middle of a snowy forest,a road in the middle of a snowy forest,1,"[road, forest, snowy, middle]",0

In [4]:
import spacy
from keybert import KeyBERT

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Initialize KeyBERT model
kw_model = KeyBERT()

# Input sentence
sentence = "Join us in our vision to create a world where everyone can achieve optimal health and well-being"
# Extract keywords
keywords = kw_model.extract_keywords(sentence, keyphrase_ngram_range=(1, 1), stop_words='english', top_n=10)

# Filter only nouns
doc = nlp(sentence)
nouns = [token.text for token in doc if token.pos_ == "NOUN"]

# Get top 2 noun keywords
noun_keywords = [keyword[0] for keyword in keywords if keyword[0] in nouns][:2]

# Print the extracted noun keywords
for noun_keyword in noun_keywords:
    print(noun_keyword)

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

health
world

In [8]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

text = "Join us in our vision to create a world where everyone can achieve optimal health and well-being."
words = nltk.word_tokenize(text)
pos_tags = nltk.pos_tag(words)

print(pos_tags)

[('Join', 'NNP'), ('us', 'PRP'), ('in', 'IN'), ('our', 'PRP$'), ('vision', 'NN'), ('to', 'TO'), ('create', 'VB'), ('a', 'DT'), ('world', 'NN'), ('where', 'WRB'), ('everyone', 'NN'), ('can', 'MD'), ('achieve', 'VB'), ('optimal', 'JJ'), ('health', 'NN'), ('and', 'CC'), ('well-being', 'NN'), ('.', '.')]

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/fatimaezzahrasounnyslitine/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [7]:
import spacy

# Load English tokenizer, POS tagger, parser, NER
nlp = spacy.load("en_core_web_sm")

text = "A road in the middle of a snowy forest."
doc = nlp(text)

# Extracting named entities, phrases, and concepts
entities = [(entity.text, entity.label_) for entity in doc.ents]
noun_chunks = [chunk.text for chunk in doc.noun_chunks]

print("Entities:", entities)
print("Noun Phrases:", noun_chunks)

Entities: []
Noun Phrases: ['A road', 'the middle', 'a snowy forest']

In [3]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Join us in our vision to create a world where everyone can achieve optimal health and well-being."
doc = nlp(text)

pos_tags = [(token.text, token.pos_) for token in doc]

print(pos_tags)

[('Join', 'VERB'), ('us', 'PRON'), ('in', 'ADP'), ('our', 'PRON'), ('vision', 'NOUN'), ('to', 'PART'), ('create', 'VERB'), ('a', 'DET'), ('world', 'NOUN'), ('where', 'SCONJ'), ('everyone', 'PRON'), ('can', 'AUX'), ('achieve', 'VERB'), ('optimal', 'ADJ'), ('health', 'NOUN'), ('and', 'CCONJ'), ('well', 'NOUN'), ('-', 'PUNCT'), ('being', 'NOUN'), ('.', 'PUNCT')]

In [2]:
import spacy

# Load the spaCy model
nlp = spacy.load("en_core_web_sm")

# The image description
text = "sea and rock cliff with grasses under cloudy sky"

# Process the text with spaCy
doc = nlp(text)

# Extracting unique nouns and adjectives
key_words = list(set([token.text for token in doc if token.pos_ in ['NOUN', 'ADJ']]))

print("Unique Key Words:", key_words)

/Users/fatimaezzahrasounnyslitine/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Unique Key Words: ['grasses', 'rock', 'sea', 'cloudy', 'sky']

In [2]:
import pandas as pd

In [17]:
# metadata=pd.read_excel("new_metadata_mixkit_unsplash_pixabay-4.xlsx")

#metadata=metadata[metadata["type"]=="image"]

from datalake import read_metadata_from_s3

metadata=read_metadata_from_s3("soulchain-dev1-output-video", "new_metadata_mixkit_unsplash_pixabay.xlsx")

In [18]:
metadata['new_description'] = metadata['new_description'].str.replace('An image of', '', regex=False)

In [19]:
# metadata=metadata[metadata["source"]=="pixabay"]
# metadata=metadata[metadata["type"]=="image"]

In [20]:
metadata

,Unnamed: 0,name,keywords,url,type,term,path_datalake,count_usage,count_edit,media_state,description,keywords_description,source,size,new_description,entities,new_keywords,most_frequent_words
0,0,21617-319452308_large.mp4,"['blood', 'medicine', 'blood cells']",https://cdn.pixabay.com/video/2019/02/23/21617...,video,health,datalake_media/video-21617-319452308_large.mp4...,1,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
1,1,8449-209292163_large.mp4,"['heart', 'heartbeat', 'slow heart']",https://cdn.pixabay.com/video/2017/03/20/8449-...,video,health,datalake_media/video-8449-209292163_large.mp4-...,0,0,useful,NaN,[],pixabay,NaN,NaN,NaN,NaN,NaN
2,2,bygTaBey1Xk.jpg,"['grass', 'shore', 'ocean', 'coast', 'beach', ...",https://images.unsplash.com/uploads/1413387620...,image,grass,datalake_media/image-bygTaBey1Xk.jpg-c8c7df3c-...,0,0,useful,sea and rock cliff with grasses under cloudy sky,"['cliff', 'grasses', 'cloudy', 'sky', 'rock']",unsplash,horizontal,the sea and cliffs in Scotland,"[('the sea', (12, 19), [(0.015625, 0.296875, 0...","['sea', 'cliff']","['sea', 'cliff']"
3,3,gXSFnk2a9V4.jpg,"['blue', 'holiday', 'geographical feature', 'a...",https://images.unsplash.com/reserve/jEs6K0y1Sb...,image,blue,datalake_media/image-gXSFnk2a9V4.jpg-a0496092-...,0,0,useful,aerial photography of seashore,"['seashore', 'aerial', 'photography']",unsplash,vertical,a beach and ocean from a hill,"[('a beach', (12, 19), [(0.015625, 0.578125, 0...","['beach', 'ocean', 'hill']","['beach', 'ocean', 'hill']"
4,4,grg6-DNJuaU.jpg,"['sea', 'jump', 'waves', 'summer', 'holiday', ...",https://images.unsplash.com/uploads/1412192004...,image,sea,datalake_media/image-grg6-DNJuaU.jpg-c2b853ee-...,0,0,useful,man surfboarding on ocean wave during daytime,"['surfboarding', 'ocean', 'wave', 'daytime', '...",unsplash,horizontal,a surfer catching a wave and a man in the wat...,"[('a surfer', (12, 20), [(0.515625, 0.140625, ...","['surfer', 'wave', 'man', 'water']","['surfer', 'wave', 'man', 'water']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14901,1767,Man skillfully practicing pirouettes in a park,"['sport', 'medium shot wid', 'exercis', 'athle...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-c11ecf93-f073-4aab-...,0,0,useful,Two cheerleader guys lifting a girl upside dow...,"['lifting', 'cheerleader', 'workout', 'pyramid...",mixkit,vertical,A video of a woman doing a squat with a traine...,"[('a woman', (11, 18), [(0.265625, 0.171875, 0...","['squat', 'park', 'man', 'trainer', 'woman', '...","['sport', 'medium shot wid', 'exercis', 'athle..."
14902,1768,Cheerleader girl in pose on top of a pyramid,"['sport', 'exercis', 'low angle shot', 'athlet...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-dee6dd45-e368-40cd-...,0,0,useful,"Cheerleader girl in pose, raising her arms on ...","['cheerleader', 'pose', 'pyramid', 'girl', 'ra...",mixkit,vertical,A video of a woman jumping in the air A video ...,"[('a woman', (11, 18), [(0.015625, 0.046875, 0...","['air', 'woman']","['sport', 'exercis', 'low angle shot', 'athlet..."
14903,1769,Cheerleader boy lifting a girl on his hands,"['sport', 'slow mot', 'exercis', 'track', 'ath...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-d3a0fcb8-e665-4c73-...,0,0,useful,Cheerleader man lifts a girl to carry her stan...,"['cheerleader', 'lifts', 'girl', 'workout', 'c...",mixkit,vertical,A video of a man and a woman on a tennis court...,"[('a man', (11, 16), [(0.265625, 0.515625, 0.7...","['expression', 'tennis', 'park', 'man', 'court...","['sport', 'slow mot', 'exercis', 'track', 'ath..."
14904,1770,Cheerleaders throwing a girl into the air at a...,"['sport', 'medium shot wid', 'exercis', 'track...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-807c3dc2-f9e7-45ce-...,0,0,useful,Cheerleading team throwing a girl who takes a ...,"['cheerleading', 'throwing', 'spin', 'girl', '...",mixkit,horizontal,A video of a group of young men playing basket...,"[('young men', (22, 31), [(0.546875, 0.515625,...","['ground', 'basketball', 'group', 'man', 'cour...","['sport', 'medium shot wid', 'exercis', 'track..."
14905,1771,Point of view fighting in a ring against a woman,"['sport', 'women', 'sport', 'fight', 'box', 'g...",https://assets.mixkit.co/videos/preview/mixkit...,video,sport,datalake_media/video-sport-58ae574d-449a-4265-...,0,0,useful,Point of view during an intense mixed martial ...,"['punches', 'martial', 'woman', 'match', 'ring']",mixkit,horizontal,A video of a female boxer throwing a punch in ...,"[('a female boxer', (11, 25), [(0.421875, 0.01...","['neon', 'police', 'man', 'punch', 'ring', 'ni...","['woman', 'ring', 'sport', 'fight', 'punch', '..."

In [9]:

def extract_noun_keywords(text, top_n=2):
    kw_model = KeyBERT()
    nlp = spacy.load("en_core_web_sm")
    keywords = kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 1), stop_words='english', top_n=10)

    doc = nlp(text)
    nouns = [token.text for token in doc if token.pos_ == "NOUN"]

    noun_keywords = [keyword[0] for keyword in keywords if keyword[0] in nouns][:top_n]

    return noun_keywords


text="a snake curled around a tree branch, with a small snake and a fruit in the background"

extract_noun_keywords(text)
# metadata['new_description_keywords'] = metadata['new_description'].apply(lambda x: extract_noun_keywords(x) if isinstance(x, str) else [])

['snake', 'tree']

In [50]:
import pandas as pd
import inflect

# Create an inflect engine
p = inflect.engine()

def to_singular_list(word_list):
    return [p.singular_noun(word) if p.singular_noun(word) else word for word in word_list]


metadata['new_description_keywords'] = metadata['new_description_keywords'].apply(to_singular_list)

/var/folders/ys/s5c8y6vx2n95hnjtr5vs5h000000gn/T/ipykernel_1009/2545655213.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata['new_description_keywords'] = metadata['new_description_keywords'].apply(to_singular_list)

In [65]:
metadata.to_csv("metadata_new_pixabay")

In [64]:
from text_to_media import find_media_best


find_media_best(['wellness', 'longevity'],[], metadata)

ValueError: malformed node or string: ['cat', 'distance']

In [52]:
import boto3
from io import BytesIO
import io
from datalake import put_image_in_s3

bucket='soulchain-dev1-output-video'
s3 = boto3.client('s3', aws_access_key_id="AKIAUJXLE2HEOGWEMCEX",aws_secret_access_key="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",region_name='eu-west-1')

with io.BytesIO() as buffer:
    metadata.to_excel(buffer, index=False)
    buffer.seek(0)
    data_bytes = buffer.read() 
put_image_in_s3(data_bytes,"soulchain-dev1-output-video", "new_new_metadata_mixkit_unsplash_pixabay.xlsx")

Media uploaded successfully to S3

In [11]:
import requests

def google_image_search(api_key, search_engine_id, query):
    url = "https://www.googleapis.com/customsearch/v1"
    params = {
        'key': api_key,
        'cx': search_engine_id,
        'q': query,
        'searchType': 'image',
        'num': 1
    }
    response = requests.get(url, params=params)
    response.raise_for_status()  # Raises an HTTPError if the HTTP request returned an unsuccessful status code
    return response.json()

# Replace these with your own API key and Search Engine ID
api_key = 'AIzaSyDIj3PxevGpBnr8MCuxX4z089o4yNQevrU'
search_engine_id = 'c6684e252cbae47c2'

# Perform a search for a single image
query = 'cats'
results = google_image_search(api_key, search_engine_id, query)

# Extract and print the image URL
if 'items' in results and len(results['items']) > 0:
    image_url = results['items'][0]['link']
    print(f"Image URL: {image_url}")
else:
    print("No image found.")

Image URL: https://cdn.britannica.com/34/235834-050-C5843610/two-different-breeds-of-cats-side-by-side-outdoors-in-the-garden.jpg